

##
## ## Default Rule
##

default: help
.PHONY: default




##
## ## Help
##

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make install'
	@echo
	@echo '	$$ make package-install'
	@echo
	@echo '	$$ make asset-install'
	@echo
	@echo '	$$ make config-install'
	@echo
.PHONY: help




##
## ## Install
##

install:
	@./install.sh
.PHONY: install


package-install:
	@./package-install.sh
.PHONY: package-install


asset-install:
	@./asset-install.sh
.PHONY: asset-install


config-install:
	@./config-install.sh
.PHONY: config-install
